articles/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^edit', views.edit_article, name='edit_article'),
    url(r'^delete$', views.delete_article, name='delete_article'),
    url(r'^comments_add$', views.comment_add, name='comment_add'),
    url(r'^comments_delete$', views.comment_delete, name='comment_delete'),
    url(r'^comments_update$', views.comment_update, name='comment_update'),
    url(r'^comments_next_page$', views.comment_next_page, name='comment_next_page'),
    url(r'^set_comment_rating$', views.set_comment_rating, name='set_comment_rating'),
    url(r'^set_article_rating$', views.set_article_rating, name='set_article_rating'),

    url(r'^(?P<article_slug>[\w-]+)$', views.full_article, name='full_article'),

    url(r'^tag/(?P<tag_slug>[\w-]+)$', views.tags, name='tags'),

    #url(r'^latest/(?P<page_number>[0-9]*)', views.news, name='news'),
)

news_blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from news_blog import settings

from articles.views import home_page, view_category, view_tags, search
from authentication.views import signin, signout
import profiles.urls

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('articles.urls', namespace='articles')),

    url(r'^login', signin, name='login'),
    url(r'^logout$', signout, name='logout'),

    url(r'^users/', include(profiles.urls, namespace='users')),

    url(r'^tags$', view_tags, name='tags'),
    url(r'^search$', search, name='search'),

    url(r'^$', home_page, name='home'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    url(r'^(?P<category_slug>[A-Za-z0-9\-\_]+)$', view_category, name='view_category'),
)

profiles/urls.py
from django.conf.urls import patterns, url
import views
from articles.views import user_articles

urlpatterns = patterns('',
    url(r'^register/$', views.create_user, name='create_user'),

    url(r'^dashboard/$', views.home_page, name='dashboard'),
    url(r'^(?P<user_name>\w+)/$', views.profile_page, name='profile_page'),

    url(r'^subscribe$', views.subscribe, name='subscribe'),
    url(r'^change_subscription$', views.change_subscr, name='change_subscr'),
    url(r'^(?P<user_name>\w+)/articles$', user_articles, name='user_articles'),
)

templates/base/base.html
{% load static %}
{% load staticfiles %}
{% load menu_extras %}
{% load footer_extras %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block page_title %}News{% endblock %}</title>

    {% block css_base %}
        <link href="{% static 'base/css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'base/css/font-awesome.css' %}" rel="stylesheet">
        <link href="{% static 'base/css/base.css' %}" rel="stylesheet">
        <link href="{% static 'base/css/menu.css' %}" rel="stylesheet">
    {% endblock %}

    {% block css %}{% endblock %}
</head>

<body>
{% block body %}
    {% block preheader %}
        <section class="container preheader">
            <nav class="user clearfix">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'users:dashboard' %}"><i class="fa fa-user"></i>&nbsp;{{ request.user.get_full_name }}</a>

                    {% if request.user.is_staff %}
                        <a href="{% url 'admin:index' %}">
                            <span class="label label-danger">Admin panel</span>
                        </a>
                    {% endif %}

                    <a href="{% url 'articles:edit_article' %}"><i class="fa fa-edit"></i>&nbsp;Write article</a>
                    <a href="{% url 'users:user_articles' request.user.username %}">My articles</a>
                    <a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>&nbsp;Sign out</a>
                {% else %}
                    <a href="{% url 'users:create_user' %}"><i class="fa fa-user"></i>&nbsp;Sign up</a>
                    <a href="{% url 'login' %}?next={{ request.path }}"><i class="fa fa-sign-in"></i>&nbsp;Log in</a>
                {% endif %}
            </nav>

            <div class="pre-header-search-form">
                <a href="{% url 'search' %}"><i class="pre-header-search-button"></i></a>
            </div>
        </section>
    {% endblock %}

    {% block navbar %}
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                {% make_menu %}
            </div>
        </nav>
    {% endblock %}

    {% block main_container %}
        <div class="container">
            {% block container %}
                <div class="row">
                    <div class="col-md-9">
                        {% block content %}{% endblock %}
                        {% block pages %}{% endblock %}
                    </div>

                    <div class="col-md-3">
                        {% block sidebar %}{% endblock %}
                    </div>
                </div>
            {% endblock %}
        </div>
    {% endblock %}

    {% block footer %}
        <footer id="footer" class="clearfix">
            <div class="container">
                <div class="row-fluid">
                    <div class="col-lg-4">
                        {% footer_top_tags %}
                    </div>

                    <div class="col-lg-4">
                        {% footer_user_tags %}

                        <section>
                            <h4>Quick search</h4>

                            <p>Type something to search on the site. Do not be afraid, take action!</p>

                            <form action="{% url 'search' %}" method="get">
                                <div class="input-append  search">
                                    <input type="text" placeholder="Your words" name="search"/>
                                    <button class="btn btn-primary btn-my">Search</button>
                                </div>
                            </form>
                        </section>
                    </div>

                    <div class="col-lg-4">
                        {% footer_latest_news %}
                    </div>
                </div>
            </div>

            <section class="footerCredits">
                <div class="container">
                    <ul class="clearfix">
                        <li>© 2014 News. All rights reserved (realy :D).</li>
                        <li><a href="#">Site Map</a></li>
                        <li><a href="#">Privacy</a></li>
                    </ul>
                </div>
            </section>
        </footer>
    {% endblock %}

    {% block js_base %}
        <script src="{% static 'base/js/jquery-1.10.2.js' %}"></script>
        <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'base/js/menu.js' %}"></script>

        <script>
            var active_menu_item = '{{ active_menu_item }}';

            var main_menu = $('#main_menu');
            main_menu.find('ul li.active').removeClass('active');

            main_menu.find('ul li[item-name=' + active_menu_item + ']').addClass('active');

            var other_menu_items = main_menu.find('ul li.parent ul li[item-name=' + active_menu_item + ']');
            if (other_menu_items.length != 0) {
                main_menu.find('ul li.parent').addClass('active');
            }
        </script>
    {% endblock %}

    {% block js %}{% endblock %}

{% endblock %}
</body>
</html>